name: Auto-publish

on:
  push:
      branches:
          - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy
      working-directory: ./
      run: |
        mkdir doc
        mkdir doc/img
        cp README.md doc/
        cp model.html doc/
        cp model.ttl doc/
        cp img/Overview.png doc/img/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         BRANCH: gh-pages
         FOLDER: doc